# Based on https://martin-renze.de/posts/gitlab-ci-releases/
# https://docs.gitlab.com/ee/user/project/releases/release_cicd_examples.html
stages:
  - build
  - release

build_job:
  stage: build
  image: composer
  script:
    - composer install
    - RELEASE_VERSION=$(grep '<version' info.xml | sed -e 's/.*<version>//' -e 's/<\/version>//')
    - mkdir build
    - zip -qr9 --exclude=.git* --exclude=build build/${CI_PROJECT_NAME}-${RELEASE_VERSION}.zip .
    - echo BUILD_JOB_ID=$CI_JOB_ID >> variables.env
    - echo BUILD_VERSION=$RELEASE_VERSION >> variables.env
  artifacts:
    paths:
      - "build/${CI_PROJECT_NAME}-${RELEASE_VERSION}.zip"
    reports:
      dotenv: variables.env
  rules:
    - if: $CI_COMMIT_TAG
  tags:
    - test-1-docker

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build_job
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release_job for $TAG"
  release:
    name: 'Release Executables $CI_COMMIT_SHORT_SHA'
    description: 'Created using the release-cli'
    tag_name: '$CI_COMMIT_SHORT_SHA'
    assets:
      links:
        - name: '$CI_PROJECT_NAME release zip'
          url: '${CI_PROJECT_URL}/-/jobs/${BUILD_JOB_ID}/artifacts/file/build/${CI_PROJECT_NAME}-${RELEASE_VERSION}.zip'
  tags:
    - test-1-docker