<?php

use CRM_Sparkpost_ExtensionUtil as E;

return [
  'sparkpost_host' => [
    'group_name' => CRM_Sparkpost::SPARKPOST_EXTENSION_SETTINGS,
    'group' => 'com.cividesk.email.sparkpost',
    'name' => 'sparkpost_host',
    'type' => 'String',
    'quick_form_type' => 'Select',
    'html_type' => 'Select',
    'html_attributes' => [],
    'default' => 'sparkpost.com',
    'add' => '4.7',
    'title' => E::ts('Sparkpost Host'),
    'is_domain' => 1,
    'is_contact' => 0,
    'pseudoconstant' => [
      'callback' => 'CRM_Sparkpost::getSparkpostHostOptions',
    ],
    'description' => E::ts('Select the host. If you are using an EU-hosted platform you will need an <a %1>European account</a>.', [1 => 'href="https://app.eu.sparkpost.com"']),
    'help_text' => E::ts('European accounts have to use *.eu.sparkpost.com'),
  ],
  'sparkpost_apiKey' => [
    'group_name' => 'SparkPost Extension Settings',
    'group' => 'com.cividesk.email.sparkpost',
    'name' => 'sparkpost_apiKey',
    'type' => 'String',
    'html_type' => 'password',
    'default' => NULL,
    'add' => '4.4',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('SparkPost REST API key'),
    'help_text' => 'You can create API keys at: https://app.sparkpost.com/account/api-keys, or https://app.eu.sparkpost.com/account/api-keys if using the EU-hosted platform.',
  ],
  'sparkpost_customCallbackUrl' => [
    'group_name' => 'SparkPost Extension Settings',
    'group' => 'com.cividesk.email.sparkpost',
    'name' => 'sparkpost_customCallbackUrl',
    'type' => 'String',
    'html_type' => 'text',
    'default' => NULL,
    'add' => '4.4',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('A custom callback URL. Useful if your site is behind a proxy (like CiviProxy)'),
    'help_text' => E::ts('A custom callback URL is useful when your site is behind a proxy (like CiviProxy)'),
  ],
  'sparkpost_useBackupMailer' => [
    'group_name' => 'SparkPost Extension Settings',
    'group' => 'com.cividesk.email.sparkpost',
    'name' => 'sparkpost_useBackupMailer',
    'type' => 'Boolean',
    'html_type' => 'radio',
    'default' => FALSE,
    'add' => '4.4',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => E::ts('Use backup mailer?'),
    'help_text' => E::ts('The backup mailer will be used if Sparkpost cannot send emails (unverified sending domain, sending limits exceeded, ...).'),
  ],
  'sparkpost_sending_quota' => [
    'name' => 'sparkpost_sending_quota',
    'type' => 'Integer',
    'html_type' => 'text',
    'default' => 65000,
    'add' => '1.7',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Monthly sending quota. This is checked against Sparkpost metrics. Above this number, a Status Check warning will be displayed, but it will not stop sending emails. It can be useful for monitoring.',
  ],
  'sparkpost_sending_quota_alert' => [
    'name' => 'sparkpost_sending_quota_alert',
    'type' => 'Integer',
    'html_type' => 'text',
    'default' => 100000,
    'add' => '1.7',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Above this number, a critical Status Check will be displayed. For now, it will not stop sending emails. It can be useful for monitoring.',
  ],
  'sparkpost_bounce_rate' => [
    'name' => 'sparkpost_bounce_rate',
    'type' => 'Integer',
    'html_type' => 'text',
    'default' => 10,
    'add' => '1.7',
    'is_domain' => 1,
    'is_contact' => 0,
    'description' => 'Raise a CiviCRM System Check alert if the perceptage of bounces is above a certain threshold. Set to 0 to disable.',
  ],
];
