-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_mailing_event_sparkpost`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_mailing_event_sparkpost
-- *
-- * FIXME
-- *
-- *******************************************************/
CREATE TABLE `civicrm_mailing_event_sparkpost` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique MailingEventSparkpost ID',
  `event_queue_id` int unsigned COMMENT 'FK File d\'attente des événements',
  `contact_id` int unsigned COMMENT 'FK de contact',
  `activity_id` int unsigned COMMENT 'FK to Activity',
  `sparkpost_event_id` int unsigned COMMENT 'External Sparkpost Event ID',
  `subject` varchar(128) COMMENT 'Subject line from the email header.',
  `bounce_class` int unsigned COMMENT 'Sparkpost bounce class',
  `error_code` int unsigned COMMENT 'Error code by which the remote server described a failed delivery attempt.',
  `num_retries` int unsigned COMMENT 'Sparkpost number of retries',
  `friendly_from` varchar(254) COMMENT 'Friendly sender or \'From\' header in the original email.',
  `rcpt_to` varchar(254) COMMENT 'Lowercase version of recipient address used on this message\'s SMTP envelope.',
  `raw_reason` varchar(254) COMMENT 'Unmodified, exact response returned by the remote server due to a failed delivery attempt',
  `reason` varchar(254) COMMENT 'Canonicalized text of the response returned by the remote server due to a failed delivery attempt.',
  `transactional` tinyint COMMENT 'Indicates if the transmission was marked as transactional.',
  `injection_time` datetime COMMENT 'Time at which this message was injected into SparkPost.',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_mailing_event_sparkpost_event_queue_id FOREIGN KEY (`event_queue_id`) REFERENCES `civicrm_mailing_event_queue`(`id`) ON DELETE SET NULL,
  CONSTRAINT FK_civicrm_mailing_event_sparkpost_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL,
  CONSTRAINT FK_civicrm_mailing_event_sparkpost_activity_id FOREIGN KEY (`activity_id`) REFERENCES `civicrm_activity`(`id`) ON DELETE SET NULL
)
ENGINE=InnoDB;
